import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/0CEVWnzH4OvQaO1CrIqOxw/Web-Components-Code-Connect?node-id=11-14&m=dev",
  {
    props: {
      title: figma.string("title"), // Maps the title property
      label: figma.string("label"), // Maps the label property (though not used in Navbar yet)
    },
    example: ({ title, label }) => html`<navbar-e
      title="${title}"
      navlabel="${label}"
    >`,
  },
)
