import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/0CEVWnzH4OvQaO1CrIqOxw/Web-Components-Code-Connect?node-id=13-28&m=dev",
  {
    props: {
      title: figma.string("title"),
      description: figma.string("description"),
      price: figma.string("price"),
      // Map the button as a child instance
      button: figma.children('Button'),
    },
    example: ({ title, description, price, button }) =>
      html`
        <product-card
          title="${title}"
          description="${description}"
          price="${price}"
          imgSrc="Your Image"
        >
          ${button} <!-- Embed the button here as a child -->
        </product-card>
      `,
  }
)
